[package]
name = "service"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
serde_json.workspace = true
opentelemetry.workspace = true
tracing-opentelemetry.workspace = true
lambda_runtime.workspace = true
tracing.workspace = true
anyhow.workspace = true
reqwest.workspace = true
aws_lambda_events.workspace = true
aws-config.workspace = true
lambda-lw-http-router.workspace = true
serde.workspace = true
lambda-otel-lite.workspace = true
aws-sdk-dynamodb.workspace = true
chrono.workspace = true
serde_dynamo.workspace = true
lazy_static.workspace = true
sha2.workspace = true
tera.workspace = true
reqwest-middleware.workspace = true
reqwest-tracing.workspace = true
thiserror.workspace = true

[[bin]]
name = "frontend"
path = "src/frontend/main.rs"

[[bin]]
name = "backend"
path = "src/backend/main.rs"
